service: go-ses-mailer
frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  # you can overwrite defaults here
  stage: prod
  region: ap-south-1

  # you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  email:
    handler: bin/mailer
    events:
      - http:
          method: post
          path: send
